### ISSUE TITLE
Rely on No Dependencies

### ISSUE THREAD

**Issue by ghost** [AlphaT3ch/Notifico-npm#1]
Currently the project relies on the request dependence which can install a lot of unnecessary code and waste a small amount of time while downloading code. We'd like this problem to be eliminated by relying on no dependencies at all.

**Comment by Klathmon** [comment]
I can take a look at this for you!

**Comment by hugoduraes** [comment]
@Klathmon hey, we both submitted a PR! :( Haven't notice you're going to work on this! Your PR is better than mine because you thought on the https use case. @AlphaT3ch please use @Klathmon's PR instead of mine! :)

**Comment by ghost** [comment]
Merged #3 by @klathmon
