### ISSUE TITLE
Rely on no dependencies

### ISSUE THREAD

**Issue by JeffResc** [AlphaT3ch/Notifico-npm#4]
Currently, the project relies on the "request" dependency which can download an amount of unnecessary code and waste a small amount of time while downloading code. We'd like this problem to be eliminated by relying on no dependencies at all. Please reply if you'd be interested in working on this issue. An example of replacing the "request" dependency can be found in [this issue](https://github.com/JeffResc/Is.gd-Node.js/issues/1).

**Comment by mccarthydanielle** [comment]
I can work on this!

**Comment by mccarthydanielle** [comment]
I do not see the request module being used in this repo. Am I missing it somewhere?

**Comment by JeffResc** [comment]
My apologies, @mccarthydanielle. I checked [npmjs.com](https://www.npmjs.com/package/notifico) and it told me that this project has that dependency, I should've checked manually as it was actually wrong. If you're still interested, the following projects have similar issues: [DroneBL-Node.js](https://github.com/JeffResc/DroneBL-Node.js/issues/6) and [SpamCop](https://github.com/JeffResc/SpamCop/issues/1)
